### ISSUE TITLE
sass-loader fails with "undefined variable"

### ISSUE THREAD

**Issue by Kelbster** [shprink/angular1.4-ES6-material-webpack-boilerplate#1]
It's possible this is user error, and I haven't configured weback.config and my app.js correctly, but,
variables in `scss/_variables.scss` such as `$gray: #CCC;` return undefined in modules outside of the scss folder.

Say we have `$gray: #CCC;` defined in `lib/scss/_variables.scss`
and
in `lib/home/home.scss`, we have `.my-toolbar { background: $gray; }`
Webpack bundle fails with: 
`Module build failed: 
background: $gray;
Undefined variable: "$gray"`
Still fails with the same error even if I `@import "../home/home.scss"`

**Comment by shprink** [comment]
Add this on top of your scss

```
@import "../scss/variables";
```

Let me know

**Comment by Kelbster** [comment]
Oh! is that because webpack needs the relative path?
That works perfectly, thank you :)
