### ISSUE TITLE
question about  complid 

### ISSUE THREAD

**Issue by nueramina** [shprink/angular1.4-ES6-material-webpack-boilerplate#7]
**\* this is my package.json content.    I put some library version update to the latest and this is my After updated an package.json  content .     After a change is an error .  How to solve this problem? ***

{
    "name": "angular1.4-ES6-material-webpack-boilerplate",
    "version": "1.0.0",
    "description": "A simple AngularJS 1.4 boilerplate using ES6, material design and webpack",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "build": "webpack -p",
        "devserver": "webpack-dev-server --port 9100 --progress --colors"
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/shprink/angular1.4-ES6-material-webpack-boilerplate.git"
    },
    "author": "shprink contact@julienrenaux.fr (http://julienrenaux.fr/)",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/shprink/angular1.4-ES6-material-webpack-boilerplate/issues"
    },
    "dependencies": {
        "angular": "~1.5.7",
        "angular-animate": "~1.5.7",
        "angular-aria": "~1.5.7",
        "angular-material": "^1.1.0-rc.5",
        "angular-ui-router": "^0.3.1",
        "font-awesome": "^4.3.0"
    },
    "homepage": "https://github.com/shprink/angular1.4-ES6-material-webpack-boilerplate",
    "devDependencies": {
        "autoprefixer-loader": "^3.2.0",
        "babel-core": "^6.10.4",
        "babel-loader": "^6.2.4",
        "css-loader": "^0.23.1",
        "file-loader": "^0.9.0",
        "html-loader": "^0.4.3",
        "html-webpack-plugin": "^2.21.0",
        "ng-annotate-loader": "~0.1.0",
        "node-sass": "^3.2.0",

```
    "sass-loader": "^3.2.1",
    "style-loader": "^0.13.1",
    "webpack": "^1.8.11",
    "webpack-dev-server": "^1.8.2"
}
```

}

this is error content

Microsoft Windows [版本 6.1.7600]  
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。                                                                                                                                                     

D:\bitbucket\angular1.4-ES6-material-webpack-boilerplate-master>npm run-service dev

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\admin.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.9.5 C:\Program Files\nodejs\node_modules\npm

D:\bitbucket\angular1.4-ES6-material-webpack-boilerplate-master>npm run-script devserver

> angular1.4-ES6-material-webpack-boilerplate@1.0.0 devserver D:\bitbucket\angular1.4-ES6-material-webpa
> ck-boilerplate-master
> webpack-dev-server --port 9100 --progress --colors

  0% compileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9100
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:84:10)

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\
npm-cli.js" "run-script" "devserver"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular1.4-ES6-material-webpack-boilerplate@1.0.0 devserver: `webpack-dev-server --port 9100 --
progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular1.4-ES6-material-webpack-boilerplate@1.0.0 devserver script 'webpack-dev-s
erver --port 9100 --progress --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular1.4-ES6-material-webpack-boilerplate p
ackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --port 9100 --progress --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular1.4-ES6-material-webpack-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular1.4-ES6-material-webpack-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\bitbucket\angular1.4-ES6-material-webpack-boilerplate-master\npm-debug.log

D:\bitbucket\angular1.4-ES6-material-webpack-boilerplate-master>

**Comment by shprink** [comment]
> Error: listen EADDRINUSE 127.0.0.1:9100

port 9100 is already in use

**Comment by nueramina** [comment]
thank you!
